// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  SENTRY_DSN: string
  SENTRY_ORG: string
  SENTRY_PROJECT: string
}
